// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBnBg5o2UuOX2m0UI3Fy62RPsuwVJNc48',
    appId: '1:872482741661:web:43627f668a024cc405e374',
    messagingSenderId: '872482741661',
    projectId: 'vegi-ecommerce',
    authDomain: 'vegi-ecommerce.firebaseapp.com',
    storageBucket: 'vegi-ecommerce.appspot.com',
    measurementId: 'G-L8PHV4K494',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMc9CEZxBIKodVmblnJSG06Z9UciZ6_b0',
    appId: '1:872482741661:android:81505610b3a6185d05e374',
    messagingSenderId: '872482741661',
    projectId: 'vegi-ecommerce',
    storageBucket: 'vegi-ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZhECTSPVW3AvPYdsqfRyhoGTn_Y4IgLs',
    appId: '1:872482741661:ios:19ddd2aad9de84dc05e374',
    messagingSenderId: '872482741661',
    projectId: 'vegi-ecommerce',
    storageBucket: 'vegi-ecommerce.appspot.com',
    iosClientId: '872482741661-uktl29h2r1htljht63b7mshpk4do2ig2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZhECTSPVW3AvPYdsqfRyhoGTn_Y4IgLs',
    appId: '1:872482741661:ios:19ddd2aad9de84dc05e374',
    messagingSenderId: '872482741661',
    projectId: 'vegi-ecommerce',
    storageBucket: 'vegi-ecommerce.appspot.com',
    iosClientId: '872482741661-uktl29h2r1htljht63b7mshpk4do2ig2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAppFlutter',
  );
}
